name: Generate Snake Game

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch:       # allows manual trigger
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Vineet2511SRM
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Push the output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
